create  database customer_behavior ;
show databases;
use customer_behavior;

select * from customer;

-- Q1 what is total revenue generated by male and female
SELECT gender,
       SUM(`Purchase Amount (USD)`) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT `Customer ID`, `Purchase Amount (USD)`
FROM customer
WHERE `Discount Applied` = 'Yes'
  AND `Purchase Amount (USD)` >= (
      SELECT AVG(`Purchase Amount (USD)`)
      FROM customer
  );
  
  -- Q3. Which are the top 5 products with the highest average review rating?
SELECT `Item Purchased`,
       ROUND(AVG(`Review Rating`), 2) AS `Average Product Rating`
FROM customer
GROUP BY `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    `Shipping Type`,
    ROUND(AVG(`Purchase Amount (USD)`), 2) AS average_purchase_amount
FROM customer
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT `Subscription Status`,
       COUNT(`Customer ID`) AS total_customers,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend
FROM customer
GROUP BY `Subscription Status`
ORDER BY total_revenue , avg_spend DESC;

-- 06. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `Item Purchased`,
       ROUND(
           100.0 * SUM(
               CASE 
                   WHEN `Discount Applied` = 'Yes' THEN 1
                   ELSE 0
               END
           ) / COUNT(*),
           2
       ) AS discount_rate
FROM customer
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7 Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
    CASE
        WHEN `Previous Purchases` = 1 THEN 'New'
        WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(`Customer ID`) AS number_of_customers
FROM customer
GROUP BY
    CASE
        WHEN `Previous Purchases` = 1 THEN 'New'
        WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END
ORDER BY number_of_customers DESC;

-- Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT 
        `Category`,
        `Item Purchased`,
        COUNT(`Customer ID`) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY `Category` 
            ORDER BY COUNT(`Customer ID`) DESC
        ) AS item_rank
    FROM customer
    GROUP BY `Category`, `Item Purchased`
)
SELECT 
    item_rank,
    `Category`,
    `Item Purchased`,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (mpre than 5 previous purchases) also likely to subscribe?
SELECT 
    `Subscription Status`,
    COUNT(`Customer ID`) AS repeat_buyers
FROM customer
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;

-- Q10. What is the revenue contribution of each age group?

SELECT
    CASE
        WHEN `Age` BETWEEN 18 AND 25 THEN '18-25'
        WHEN `Age` BETWEEN 26 AND 35 THEN '26-35'
        WHEN `Age` BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END AS age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q11. Which product category generates the highest average purchase amount?
SELECT
    `Category`,
    ROUND(AVG(`Purchase Amount (USD)`), 2) AS average_purchase_amount
FROM customer
GROUP BY `Category`
ORDER BY average_purchase_amount DESC;

-- Q12. Rank customers based on their purchase amount from highest to lowest.

SELECT
    `Customer ID`,
    SUM(`Purchase Amount (USD)`) AS total_purchase,
    DENSE_RANK() OVER (
        ORDER BY SUM(`Purchase Amount (USD)`) DESC
    ) AS purchase_rank
FROM customer
GROUP BY `Customer ID`;

-- Q13. For each age group, find the percentage contribution to the total revenue.
SELECT 
    age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue,
    ROUND(
        SUM(`Purchase Amount (USD)`) * 100.0 / 
        SUM(SUM(`Purchase Amount (USD)`)) OVER (),
        2
    ) AS revenue_percentage
FROM (
    SELECT
        CASE
            WHEN `Age` BETWEEN 18 AND 25 THEN '18-25'
            WHEN `Age` BETWEEN 26 AND 35 THEN '26-35'
            WHEN `Age` BETWEEN 36 AND 50 THEN '36-50'
            ELSE '50+'
        END AS age_group,
        `Purchase Amount (USD)`
    FROM customer
) AS age_data
GROUP BY age_group
ORDER BY revenue_percentage DESC;
-- Q14. Which 10 locations generate the most revenue, and what's the average order value in each?

SELECT 
    Location,
    COUNT(`Customer ID`) AS total_orders,
    SUM(`Purchase Amount (USD)`) AS total_revenue,
    ROUND(AVG(`Purchase Amount (USD)`),2) AS avg_order_value
FROM customer
GROUP BY Location
ORDER BY total_revenue DESC
LIMIT 10;


-- Q15. How does revenue and average order value shift by season, and what % of total revenue does each season contribute?
SELECT 
    Season,
    COUNT(*) AS total_orders,
    SUM(`Purchase Amount (USD)`) AS total_revenue,
    ROUND(AVG(`Purchase Amount (USD)`),2) AS avg_purchase_amount,
    ROUND(
        100.0 * SUM(`Purchase Amount (USD)`) /
        SUM(SUM(`Purchase Amount (USD)`)) OVER (),2
    ) AS pct_of_total_revenue
FROM customer
GROUP BY Season
ORDER BY total_revenue DESC;


-- Q16. Which purchase-frequency segments drive the most revenue?

SELECT 
    `Frequency of Purchases`,
    COUNT(*) AS customers,
    SUM(`Purchase Amount (USD)`) AS total_revenue,
    ROUND(AVG(`Purchase Amount (USD)`),2) AS avg_spend
FROM customer
GROUP BY `Frequency of Purchases`
ORDER BY total_revenue DESC;


-- High-value, low-frequency customers (win-back list)

SELECT 
    `Customer ID`,
    `Purchase Amount (USD)`,
    `Frequency of Purchases`
FROM customer
WHERE `Frequency of Purchases` IN ('Annually','Every 3 Months')
AND `Purchase Amount (USD)` >
(
    SELECT AVG(`Purchase Amount (USD)`)
    FROM customer
)
ORDER BY `Purchase Amount (USD)` DESC;


-- Q17. Which payment methods are most used, and do certain methods correlate with higher average spend?

SELECT 
    `Payment Method`,
    COUNT(*) AS total_transactions,
    ROUND(
        100.0 * COUNT(*) / SUM(COUNT(*)) OVER (),2
    ) AS pct_of_transactions,
    ROUND(AVG(`Purchase Amount (USD)`),2) AS avg_spend
FROM customer
GROUP BY `Payment Method`
ORDER BY total_transactions DESC;
-- Q18. What's the best-selling size within each product category?
WITH size_counts AS
(
    SELECT 
        Category,
        Size,
        COUNT(*) AS total_orders,
        ROW_NUMBER() OVER
        (
            PARTITION BY Category
            ORDER BY COUNT(*) DESC
        ) AS rnk
    FROM customer
    GROUP BY Category, Size
)

SELECT 
    Category,
    Size,
    total_orders
FROM size_counts
WHERE rnk = 1;


-- Q19. What are the top 5 best-selling colors overall, and how much revenue do they generate?

SELECT 
    Color,
    COUNT(*) AS total_orders,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer
GROUP BY Color
ORDER BY total_orders DESC
LIMIT 5;


-- Q20. Estimated customer lifetime value (CLV) for subscribers vs non-subscribers

SELECT 
    `Subscription Status`,
    ROUND(AVG(`Previous Purchases`),2) AS avg_previous_purchases,
    ROUND(
        AVG(`Previous Purchases` * `Purchase Amount (USD)`),
        2
    ) AS avg_estimated_clv
FROM customer
GROUP BY `Subscription Status`;